import React, { useState } from 'react';

const TOPIC_VOCAB = {
  t1: ["planet", "telescope", "orbit", "space", "star", "galaxy", "astronomer"],
  t2: ["stock", "inflation", "market", "economy", "bank", "investor", "dividend"],
  t3: ["doctor", "medicine", "hospital", "patient", "treatment", "virus", "vaccine"]
};

export default function LdaTopicSandbox() {
  const [w1, setW1] = useState(50);
  const [w2, setW2] = useState(30);
  const [w3, setW3] = useState(20);

  const total = w1 + w2 + w3 || 1;
  const p1 = w1 / total;
  const p2 = w2 / total;
  const p3 = w3 / total;

  return (
    <div className="space-y-4 text-xs font-sans">
      <p className="text-[#57534e] dark:text-[#a8a29e]">
        Simulate Topic Discovery: Adjust the sliders below to see how an article blends words from three different topics:
      </p>

      <div className="space-y-3 p-4 bg-white dark:bg-[#1c1e21] rounded-xl border border-[#e5e2da] dark:border-[#2e3238]">
        <div>
          <div className="flex justify-between font-mono text-[11px] mb-1">
            <span className="text-[#1f2d3d] dark:text-[#8ba4be] font-medium">Topic 1: Space & Astronomy</span>
            <span className="font-semibold">{Math.round(p1 * 100)}%</span>
          </div>
          <input
            type="range"
            min="0"
            max="100"
            value={w1}
            onChange={(e) => setW1(parseInt(e.target.value))}
            className="w-full accent-[#1f2d3d] dark:accent-[#8ba4be]"
          />
        </div>

        <div>
          <div className="flex justify-between font-mono text-[11px] mb-1">
            <span className="text-[#926c2e] dark:text-[#d4af66] font-medium">Topic 2: Business & Finance</span>
            <span className="font-semibold">{Math.round(p2 * 100)}%</span>
          </div>
          <input
            type="range"
            min="0"
            max="100"
            value={w2}
            onChange={(e) => setW2(parseInt(e.target.value))}
            className="w-full accent-[#926c2e] dark:accent-[#d4af66]"
          />
        </div>

        <div>
          <div className="flex justify-between font-mono text-[11px] mb-1">
            <span className="text-[#2d4a3e] dark:text-[#76a992] font-medium">Topic 3: Health & Medicine</span>
            <span className="font-semibold">{Math.round(p3 * 100)}%</span>
          </div>
          <input
            type="range"
            min="0"
            max="100"
            value={w3}
            onChange={(e) => setW3(parseInt(e.target.value))}
            className="w-full accent-[#2d4a3e] dark:accent-[#76a992]"
          />
        </div>
      </div>

      <div className="p-4 bg-white dark:bg-[#1c1e21] rounded-xl border border-[#e5e2da] dark:border-[#2e3238] space-y-2">
        <span className="font-serif text-sm font-medium text-[#1c1917] dark:text-[#f5f2ea] block">
          Words Generated by This Topic Mix:
        </span>
        <div className="flex flex-wrap gap-2 pt-1">
          {TOPIC_VOCAB.t1.slice(0, Math.round(p1 * 6) + 1).map(w => (
            <span key={w} className="px-2.5 py-1 rounded-md bg-[#edf2f7] text-[#1f2d3d] border border-[#d2dce6] font-mono text-xs dark:bg-[#1e2730] dark:text-[#8ba4be]">
              {w}
            </span>
          ))}
          {TOPIC_VOCAB.t2.slice(0, Math.round(p2 * 6) + 1).map(w => (
            <span key={w} className="px-2.5 py-1 rounded-md bg-[#f7f2e7] text-[#926c2e] border border-[#e8dcc4] font-mono text-xs dark:bg-[#2e291f] dark:text-[#d4af66]">
              {w}
            </span>
          ))}
          {TOPIC_VOCAB.t3.slice(0, Math.round(p3 * 6) + 1).map(w => (
            <span key={w} className="px-2.5 py-1 rounded-md bg-[#e8efe9] text-[#2d4a3e] border border-[#2d4a3e]/30 font-mono text-xs dark:bg-[#22352c] dark:text-[#76a992]">
              {w}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
